import type { InstrumentDefinition } from "../types"

// ─── Registry ─────────────────────────────────────────────────────────────────

const _registry = new Map<string, InstrumentDefinition>()

export function registerInstrument(def: InstrumentDefinition): void {
  _registry.set(def.id, def)
}

export function getInstrument(id: string): InstrumentDefinition | null {
  return _registry.get(id) ?? null
}

export function getAllInstruments(): InstrumentDefinition[] {
  return Array.from(_registry.values())
}

// ─── Canonical Instruments ────────────────────────────────────────────────────

const EUR_30M: InstrumentDefinition = {
  id: "6e",
  underlyingId: "eurusd",
  marketType: "futures",
  assetClass: "forex_futures",
  assetType: "futures",
  name: "Euro FX Futures (6E)",
  exchange: "CME",
  venue: "CME",
  exchangeTimezone: "America/Chicago",
  tradingCalendar: "cme_fx",
  historicalProvider: "tradingview",
  historicalSymbol: "CME:6E1!",
  historicalAvailability: "ready",
  liveProvider: "tradingview",
  liveSymbol: "6E1!",
  liveAvailability: "ready",
  tickSize: 0.00005,
  precision: 5,
  multiplier: 125_000,
  supportedTimeframes: ["1m", "5m", "15m", "30m", "1h", "4h", "1d"],
  electronicSession: {
    description: "CME 6E electronic session",
    timezone: "America/Chicago",
    openDow: 0,   // Sunday
    openHour: 17,
    closeDow: 4,  // Friday
    closeHour: 16,
  },
  maintenanceBreak: {
    startHour: 16,
    endHour: 17,
    timezone: "America/Chicago",
    appliesDow: [0, 1, 2, 3, 4], // Sun–Thu
    description: "CME daily maintenance 16:00–17:00 CT",
  },
  strategyTradingWindow: {
    timezone: "Europe/Berlin",
    startHour: 9,
    startMin: 0,
    endHour: 12,
    endMin: 30,
    tradeDays: [1, 2, 3, 4], // Tue–Fri
    note: "EUR_30M strategy window",
  },
  proxyAvailable: false,
  proxyInstrumentId: null,
}

const EURUSD_CFD: InstrumentDefinition = {
  id: "eurusd",
  underlyingId: "eurusd",
  marketType: "cfd",
  assetClass: "fx_cfd",
  assetType: "cfd",
  name: "EUR/USD CFD",
  exchange: null,
  venue: "OANDA",
  exchangeTimezone: "Europe/London",
  tradingCalendar: "fx_24h",
  historicalProvider: "tradingview",
  historicalSymbol: "OANDA:EURUSD",
  historicalAvailability: "ready",
  liveProvider: "tradingview",
  liveSymbol: "EURUSD",
  liveAvailability: "ready",
  tickSize: 0.00001,
  precision: 5,
  multiplier: null,
  supportedTimeframes: ["1m", "5m", "15m", "30m", "1h"],
  electronicSession: null,
  maintenanceBreak: null,
  strategyTradingWindow: null,
  proxyAvailable: true,
  proxyInstrumentId: "6e",
}

const GBPUSD_CFD: InstrumentDefinition = {
  id: "gbpusd",
  underlyingId: "gbpusd",
  marketType: "cfd",
  assetClass: "fx_cfd",
  assetType: "cfd",
  name: "GBP/USD CFD",
  exchange: null,
  venue: "OANDA",
  exchangeTimezone: "Europe/London",
  tradingCalendar: "fx_24h",
  historicalProvider: "tradingview",
  historicalSymbol: "OANDA:GBPUSD",
  historicalAvailability: "ready",
  liveProvider: "tradingview",
  liveSymbol: "GBPUSD",
  liveAvailability: "ready",
  tickSize: 0.00001,
  precision: 5,
  multiplier: null,
  supportedTimeframes: ["1m", "5m", "15m", "30m", "1h"],
  electronicSession: null,
  maintenanceBreak: null,
  strategyTradingWindow: null,
  proxyAvailable: true,
  proxyInstrumentId: "6b",
}

const USDCHF_CFD: InstrumentDefinition = {
  id: "usdchf",
  underlyingId: "usdchf",
  marketType: "cfd",
  assetClass: "fx_cfd",
  assetType: "cfd",
  name: "USD/CHF CFD",
  exchange: null,
  venue: "OANDA",
  exchangeTimezone: "Europe/Zurich",
  tradingCalendar: "fx_24h",
  historicalProvider: "tradingview",
  historicalSymbol: "OANDA:USDCHF",
  historicalAvailability: "ready",
  liveProvider: "tradingview",
  liveSymbol: "USDCHF",
  liveAvailability: "ready",
  tickSize: 0.00001,
  precision: 5,
  multiplier: null,
  supportedTimeframes: ["1m", "5m", "15m", "30m", "1h", "1d"],
  electronicSession: null,
  maintenanceBreak: null,
  strategyTradingWindow: null,
  proxyAvailable: true,
  proxyInstrumentId: "6s",
}

const DE30EUR_CFD: InstrumentDefinition = {
  id: "de30eur",
  underlyingId: "dax",
  marketType: "cfd",
  assetClass: "fx_cfd",
  assetType: "cfd",
  name: "DAX CFD (DE30EUR)",
  exchange: null,
  venue: "OANDA",
  exchangeTimezone: "Europe/Berlin",
  tradingCalendar: "eurex_fdax",
  historicalProvider: "tradingview",
  historicalSymbol: "OANDA:DE30EUR",
  historicalAvailability: "ready",
  liveProvider: "tradingview",
  liveSymbol: "DE30EUR",
  liveAvailability: "ready",
  tickSize: 0.1,
  precision: 1,
  multiplier: null,
  supportedTimeframes: ["1m", "5m", "15m", "30m", "1h", "2h", "1d"],
  electronicSession: null,
  maintenanceBreak: null,
  strategyTradingWindow: null,
  proxyAvailable: false,
  proxyInstrumentId: null,
}

const NAS100USD_CFD: InstrumentDefinition = {
  id: "nas100usd",
  underlyingId: "nasdaq100",
  marketType: "cfd",
  assetClass: "fx_cfd",
  assetType: "cfd",
  name: "Nasdaq 100 CFD (NAS100USD)",
  exchange: null,
  venue: "OANDA",
  exchangeTimezone: "America/New_York",
  tradingCalendar: "cme_equity",
  historicalProvider: "tradingview",
  historicalSymbol: "OANDA:NAS100USD",
  historicalAvailability: "ready",
  liveProvider: "tradingview",
  liveSymbol: "NAS100USD",
  liveAvailability: "ready",
  tickSize: 0.1,
  precision: 1,
  multiplier: null,
  supportedTimeframes: ["1m", "5m", "15m", "30m", "1h", "1d"],
  electronicSession: null,
  maintenanceBreak: null,
  strategyTradingWindow: null,
  proxyAvailable: false,
  proxyInstrumentId: null,
}

const GBP_FUTURES: InstrumentDefinition = {
  id: "6b",
  underlyingId: "gbpusd",
  marketType: "futures",
  assetClass: "forex_futures",
  assetType: "futures",
  name: "British Pound Futures (6B)",
  exchange: "CME",
  venue: "CME",
  exchangeTimezone: "America/Chicago",
  tradingCalendar: "cme_fx",
  historicalProvider: "tradingview",
  historicalSymbol: "CME:6B1!",
  historicalAvailability: "ready",
  liveProvider: "tradingview",
  liveSymbol: "6B1!",
  liveAvailability: "ready",
  tickSize: 0.0001,
  precision: 4,
  multiplier: 62_500,
  supportedTimeframes: ["1m", "5m", "15m", "30m", "1h", "4h", "1d"],
  electronicSession: {
    description: "CME 6B electronic session",
    timezone: "America/Chicago",
    openDow: 0,
    openHour: 17,
    closeDow: 4,
    closeHour: 16,
  },
  maintenanceBreak: {
    startHour: 16,
    endHour: 17,
    timezone: "America/Chicago",
    appliesDow: [0, 1, 2, 3, 4],
    description: "CME daily maintenance 16:00-17:00 CT",
  },
  strategyTradingWindow: null,
  proxyAvailable: false,
  proxyInstrumentId: null,
}

const CHF_FUTURES: InstrumentDefinition = {
  id: "6s",
  underlyingId: "usdchf",
  marketType: "futures",
  assetClass: "forex_futures",
  assetType: "futures",
  name: "Swiss Franc Futures (6S)",
  exchange: "CME",
  venue: "CME",
  exchangeTimezone: "America/Chicago",
  tradingCalendar: "cme_fx",
  historicalProvider: "tradingview",
  historicalSymbol: "CME:6S1!",
  historicalAvailability: "ready",
  liveProvider: "tradingview",
  liveSymbol: "6S1!",
  liveAvailability: "ready",
  tickSize: 0.0001,
  precision: 4,
  multiplier: 125_000,
  supportedTimeframes: ["1m", "5m", "15m", "30m", "1h", "4h", "1d"],
  electronicSession: {
    description: "CME 6S electronic session",
    timezone: "America/Chicago",
    openDow: 0,
    openHour: 17,
    closeDow: 4,
    closeHour: 16,
  },
  maintenanceBreak: {
    startHour: 16,
    endHour: 17,
    timezone: "America/Chicago",
    appliesDow: [0, 1, 2, 3, 4],
    description: "CME daily maintenance 16:00-17:00 CT",
  },
  strategyTradingWindow: null,
  proxyAvailable: false,
  proxyInstrumentId: null,
}

const GC: InstrumentDefinition = {
  id: "gc",
  underlyingId: "gold",
  marketType: "futures",
  assetClass: "commodity_futures",
  assetType: "futures",
  name: "Gold Futures (GC)",
  exchange: "COMEX",
  venue: "COMEX",
  exchangeTimezone: "America/New_York",
  tradingCalendar: "comex_gc",
  historicalProvider: "tradingview",
  historicalSymbol: "COMEX:GC1!",
  historicalAvailability: "ready",
  liveProvider: "tradingview",
  liveSymbol: "GC1!",
  liveAvailability: "ready",
  tickSize: 0.1,
  precision: 1,
  multiplier: 100,
  supportedTimeframes: ["1m", "5m", "15m", "30m", "1h", "4h", "1d"],
  electronicSession: {
    description: "COMEX GC electronic session",
    timezone: "America/New_York",
    openDow: 0,
    openHour: 18,
    closeDow: 4,
    closeHour: 17,
  },
  maintenanceBreak: {
    startHour: 17,
    endHour: 18,
    timezone: "America/New_York",
    appliesDow: [0, 1, 2, 3, 4],
    description: "COMEX daily maintenance 17:00–18:00 ET",
  },
  strategyTradingWindow: null,
  proxyAvailable: false,
  proxyInstrumentId: null,
}

const YM: InstrumentDefinition = {
  id: "ym",
  underlyingId: "dowjones",
  marketType: "futures",
  assetClass: "equity_index_futures",
  assetType: "futures",
  name: "Dow Jones Futures (YM)",
  exchange: "CBOT",
  venue: "CBOT",
  exchangeTimezone: "America/Chicago",
  tradingCalendar: "cme_equity",
  historicalProvider: "tradingview",
  historicalSymbol: "CBOT:YM1!",
  historicalAvailability: "ready",
  liveProvider: "tradingview",
  liveSymbol: "YM1!",
  liveAvailability: "ready",
  tickSize: 1,
  precision: 0,
  multiplier: 5,
  supportedTimeframes: ["1m", "5m", "15m", "30m", "1h", "4h", "1d"],
  electronicSession: {
    description: "CME YM electronic session",
    timezone: "America/Chicago",
    openDow: 0,
    openHour: 17,
    closeDow: 4,
    closeHour: 16,
  },
  maintenanceBreak: {
    startHour: 16,
    endHour: 17,
    timezone: "America/Chicago",
    appliesDow: [0, 1, 2, 3, 4],
    description: "CME daily maintenance 16:00–17:00 CT",
  },
  strategyTradingWindow: null,
  proxyAvailable: false,
  proxyInstrumentId: null,
}

const NQ: InstrumentDefinition = {
  id: "nq",
  underlyingId: "nasdaq100",
  marketType: "futures",
  assetClass: "equity_index_futures",
  assetType: "futures",
  name: "Nasdaq 100 Futures (NQ)",
  exchange: "CME",
  venue: "CME",
  exchangeTimezone: "America/Chicago",
  tradingCalendar: "cme_equity",
  historicalProvider: "tradingview",
  historicalSymbol: "CME_MINI:NQ1!",
  historicalAvailability: "ready",
  liveProvider: "tradingview",
  liveSymbol: "NQ1!",
  liveAvailability: "ready",
  tickSize: 0.25,
  precision: 2,
  multiplier: 20,
  supportedTimeframes: ["1m", "5m", "15m", "30m", "1h", "4h", "1d"],
  electronicSession: {
    description: "CME NQ electronic session",
    timezone: "America/Chicago",
    openDow: 0,
    openHour: 17,
    closeDow: 4,
    closeHour: 16,
  },
  maintenanceBreak: {
    startHour: 16,
    endHour: 17,
    timezone: "America/Chicago",
    appliesDow: [0, 1, 2, 3, 4],
    description: "CME daily maintenance 16:00–17:00 CT",
  },
  strategyTradingWindow: null,
  proxyAvailable: false,
  proxyInstrumentId: null,
}

const ES: InstrumentDefinition = {
  id: "es",
  underlyingId: "sp500",
  marketType: "futures",
  assetClass: "equity_index_futures",
  assetType: "futures",
  name: "S&P 500 Futures (ES)",
  exchange: "CME",
  venue: "CME",
  exchangeTimezone: "America/Chicago",
  tradingCalendar: "cme_equity",
  historicalProvider: "tradingview",
  historicalSymbol: "CME:ES1!",
  historicalAvailability: "ready",
  liveProvider: "tradingview",
  liveSymbol: "ES1!",
  liveAvailability: "ready",
  tickSize: 0.25,
  precision: 2,
  multiplier: 50,
  supportedTimeframes: ["1m", "5m", "15m", "30m", "1h", "4h", "1d"],
  electronicSession: {
    description: "CME ES electronic session",
    timezone: "America/Chicago",
    openDow: 0,
    openHour: 17,
    closeDow: 4,
    closeHour: 16,
  },
  maintenanceBreak: {
    startHour: 16,
    endHour: 17,
    timezone: "America/Chicago",
    appliesDow: [0, 1, 2, 3, 4],
    description: "CME daily maintenance 16:00–17:00 CT",
  },
  strategyTradingWindow: null,
  proxyAvailable: false,
  proxyInstrumentId: null,
}

const FDAX: InstrumentDefinition = {
  id: "fdax",
  underlyingId: "dax",
  marketType: "futures",
  assetClass: "equity_index_futures",
  assetType: "futures",
  name: "DAX Futures (FDAX)",
  exchange: "EUREX",
  venue: "EUREX",
  exchangeTimezone: "Europe/Berlin",
  tradingCalendar: "eurex_fdax",
  historicalProvider: "tradingview",
  historicalSymbol: "EUREX:FDAX1!",
  historicalAvailability: "ready",
  liveProvider: "tradingview",
  liveSymbol: "FDAX1!",
  liveAvailability: "ready",
  tickSize: 0.5,
  precision: 1,
  multiplier: 25,
  supportedTimeframes: ["1m", "5m", "15m", "30m", "1h", "2h", "4h", "1d"],
  electronicSession: {
    description: "EUREX FDAX trading session",
    timezone: "Europe/Berlin",
    openDow: 1,
    openHour: 8,
    closeDow: 5,
    closeHour: 22,
  },
  maintenanceBreak: null,
  strategyTradingWindow: null,
  proxyAvailable: false,
  proxyInstrumentId: null,
}

// ─── Register all ─────────────────────────────────────────────────────────────

const QQQ_ETF: InstrumentDefinition = {
  id: "qqq",
  underlyingId: "nasdaq100",
  marketType: "etf",
  assetClass: "etf",
  assetType: "etf",
  name: "Invesco QQQ Trust",
  exchange: "NASDAQ",
  venue: "BATS",
  exchangeTimezone: "America/New_York",
  tradingCalendar: "us_equity",
  historicalProvider: "tradingview",
  historicalSymbol: "BATS:QQQ",
  historicalAvailability: "ready",
  liveProvider: "tradingview",
  liveSymbol: "QQQ",
  liveAvailability: "ready",
  tickSize: 0.01,
  precision: 2,
  multiplier: null,
  supportedTimeframes: ["1m", "5m", "15m", "30m", "1h", "1d"],
  electronicSession: null,
  maintenanceBreak: null,
  strategyTradingWindow: null,
  proxyAvailable: false,
  proxyInstrumentId: null,
}

;[
  EUR_30M,
  EURUSD_CFD,
  GBPUSD_CFD,
  USDCHF_CFD,
  DE30EUR_CFD,
  NAS100USD_CFD,
  GBP_FUTURES,
  CHF_FUTURES,
  GC,
  YM,
  NQ,
  ES,
  FDAX,
  QQQ_ETF,
].forEach(registerInstrument)

export {
  EUR_30M,
  EURUSD_CFD,
  GBPUSD_CFD,
  USDCHF_CFD,
  DE30EUR_CFD,
  NAS100USD_CFD,
  GBP_FUTURES,
  CHF_FUTURES,
  GC,
  YM,
  NQ,
  ES,
  FDAX,
  QQQ_ETF,
}
