/** Legacy seasonality asset metadata — used by seasonalityAssetRegistry to build enabled list. */
import type { SeasonalAssetDef } from "@/lib/seasonality/walkForward/assetManifest";

const RAW_PARTS = "trading_dashboard/data/raw/history_parts";

export const LEGACY_SEASONAL_ASSET_DEFS: SeasonalAssetDef[] = [
  // ── Agrar ────────────────────────────────────────────────────────────────
  {
    assetId: "wheat",
    symbol: "CBOT:ZW1!",
    displayName: "Standard Weizen",
    displayNameShort: "Wheat",
    category: "Agrar",
    csvFile: "full_history_validated/CBOT_ZW1_TV_MERGED_FULL_HISTORY_daily.csv",
    exchange: "CBOT",
    backadjustmentStatus: "assumed_backadjusted",
    marketType: "continuous_futures",
    iconKey: "wheat",
    firstDateEstimate: "1970-01-05",
    lastDateEstimate: "2026-05-15",
    completeYearsEstimate: 20,
  },
  {
    assetId: "soybeans",
    symbol: "CBOT:ZS1!",
    displayName: "Soybeans / Sojabohnen",
    displayNameShort: "Soybeans",
    category: "Agrar",
    csvFile: "full_history_validated/CBOT_ZS1_TV_MERGED_FULL_HISTORY_daily.csv",
    exchange: "CBOT",
    backadjustmentStatus: "assumed_backadjusted",
    marketType: "continuous_futures",
    iconKey: "soybeans",
    firstDateEstimate: "1968-12-05",
    lastDateEstimate: "2026-05-15",
    completeYearsEstimate: 20,
  },
  {
    assetId: "corn",
    symbol: "CBOT:ZC1!",
    displayName: "Corn / Mais",
    displayNameShort: "Corn",
    category: "Agrar",
    csvFile: "full_history_validated/CBOT_ZC1_TV_MERGED_FULL_HISTORY_daily.csv",
    exchange: "CBOT",
    backadjustmentStatus: "assumed_backadjusted",
    marketType: "continuous_futures",
    iconKey: "corn",
    firstDateEstimate: "1970-01-05",
    lastDateEstimate: "2026-05-15",
    completeYearsEstimate: 20,
  },
  {
    assetId: "cocoa",
    symbol: "ICEUS:CC1!",
    displayName: "Cocoa / Kakao",
    displayNameShort: "Cocoa",
    category: "Agrar",
    csvFile: "full_history_validated/ICEUS_CC1_TV_MERGED_FULL_HISTORY_daily.csv",
    exchange: "ICE US",
    backadjustmentStatus: "assumed_backadjusted",
    marketType: "continuous_futures",
    iconKey: "cocoa",
    firstDateEstimate: "1979-12-19",
    lastDateEstimate: "2026-05-15",
    completeYearsEstimate: 20,
  },
  {
    assetId: "coffee",
    symbol: "ICEUS:KC1!",
    displayName: "Coffee / Kaffee",
    displayNameShort: "Coffee",
    category: "Agrar",
    csvFile: "full_history_validated/ICEUS_KC1_TV_MERGED_FULL_HISTORY_daily.csv",
    exchange: "ICE US",
    backadjustmentStatus: "assumed_backadjusted",
    marketType: "continuous_futures",
    iconKey: "coffee",
    firstDateEstimate: "1973-08-17",
    lastDateEstimate: "2026-05-15",
    completeYearsEstimate: 20,
  },
  {
    assetId: "sugar",
    symbol: "ICEUS:SB1!",
    displayName: "Sugar No. 11 / Zucker",
    displayNameShort: "Sugar",
    category: "Agrar",
    csvFile: "full_history_validated/ICEUS_SB1_TV_MERGED_FULL_HISTORY_daily.csv",
    exchange: "ICE US",
    backadjustmentStatus: "assumed_backadjusted",
    marketType: "continuous_futures",
    iconKey: "sugar",
    firstDateEstimate: "1971-10-04",
    lastDateEstimate: "2026-05-15",
    completeYearsEstimate: 20,
  },
  {
    assetId: "cotton",
    symbol: "ICEUS:CT1!",
    displayName: "Cotton No. 2 / Baumwolle",
    displayNameShort: "Cotton",
    category: "Agrar",
    csvFile: "full_history_validated/ICEUS_CT1_TV_MERGED_FULL_HISTORY_daily.csv",
    exchange: "ICE US",
    backadjustmentStatus: "assumed_backadjusted",
    marketType: "continuous_futures",
    iconKey: "cotton",
    firstDateEstimate: "1972-08-22",
    lastDateEstimate: "2026-05-15",
    completeYearsEstimate: 20,
  },
  {
    assetId: "orangejuice",
    symbol: "ICEUS:OJ1!",
    displayName: "Orange Juice / OJ",
    displayNameShort: "OJ",
    category: "Agrar",
    csvFile: "full_history_validated/ICEUS_OJ1_TV_MERGED_FULL_HISTORY_daily.csv",
    exchange: "ICE US",
    backadjustmentStatus: "assumed_backadjusted",
    marketType: "continuous_futures",
    iconKey: "orangeJuice",
    firstDateEstimate: "1970-01-05",
    lastDateEstimate: "2026-05-15",
    completeYearsEstimate: 20,
  },

  // ── Metalle ──────────────────────────────────────────────────────────────
  {
    assetId: "xauusd",
    symbol: "XAUUSD",
    displayName: "Gold Spot",
    displayNameShort: "Gold",
    category: "Metalle",
    csvFile: "XAUUSD.csv",
    csvDir: RAW_PARTS,
    exchange: "OTC Spot",
    backadjustmentStatus: "unknown",
    marketType: "spot",
    iconKey: "gold",
    firstDateEstimate: "2000-08-30",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },
  {
    assetId: "xagusd",
    symbol: "XAGUSD",
    displayName: "Silver Spot",
    displayNameShort: "Silver",
    category: "Metalle",
    csvFile: "XAGUSD.csv",
    csvDir: RAW_PARTS,
    exchange: "OTC Spot",
    backadjustmentStatus: "unknown",
    marketType: "spot",
    iconKey: "silver",
    firstDateEstimate: "2000-08-30",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },
  {
    assetId: "copper",
    symbol: "COPPER",
    displayName: "Copper Spot",
    displayNameShort: "Copper",
    category: "Metalle",
    csvFile: "COPPER.csv",
    csvDir: RAW_PARTS,
    exchange: "OTC Spot",
    backadjustmentStatus: "unknown",
    marketType: "spot",
    iconKey: "copper",
    firstDateEstimate: "2000-08-30",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },
  {
    assetId: "xptusd",
    symbol: "XPTUSD",
    displayName: "Platinum Spot",
    displayNameShort: "Platinum",
    category: "Metalle",
    csvFile: "XPTUSD.csv",
    csvDir: RAW_PARTS,
    exchange: "OTC Spot",
    backadjustmentStatus: "unknown",
    marketType: "spot",
    iconKey: "platinum",
    firstDateEstimate: "1997-10-29",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },
  {
    assetId: "xpdusd",
    symbol: "XPDUSD",
    displayName: "Palladium Spot",
    displayNameShort: "Palladium",
    category: "Metalle",
    csvFile: "XPDUSD.csv",
    csvDir: RAW_PARTS,
    exchange: "OTC Spot",
    backadjustmentStatus: "unknown",
    marketType: "spot",
    iconKey: "palladium",
    firstDateEstimate: "1998-09-28",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },

  // ── Energie ──────────────────────────────────────────────────────────────
  {
    assetId: "diesel",
    symbol: "DIESEL",
    displayName: "Diesel / ULSD Spot",
    displayNameShort: "Diesel",
    category: "Energie",
    csvFile: "DIESEL.csv",
    csvDir: RAW_PARTS,
    exchange: "OTC Spot",
    backadjustmentStatus: "unknown",
    marketType: "spot",
    iconKey: "oil",
    firstDateEstimate: "2000-09-01",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },

  // ── FX ───────────────────────────────────────────────────────────────────
  {
    assetId: "usdjpy",
    symbol: "USDJPY",
    displayName: "USD/JPY",
    displayNameShort: "USD/JPY",
    category: "FX",
    csvFile: "USDJPY.csv",
    csvDir: RAW_PARTS,
    exchange: "OTC FX",
    backadjustmentStatus: "unknown",
    marketType: "spot",
    iconKey: "usdjpy",
    firstDateEstimate: "2006-03-02",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },
  {
    assetId: "usdchf",
    symbol: "USDCHF",
    displayName: "USD/CHF",
    displayNameShort: "USD/CHF",
    category: "FX",
    csvFile: "USDCHF.csv",
    csvDir: RAW_PARTS,
    exchange: "OTC FX",
    backadjustmentStatus: "unknown",
    marketType: "spot",
    iconKey: "usdchf",
    firstDateEstimate: "2006-03-02",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },
  {
    assetId: "usdcad",
    symbol: "USDCAD",
    displayName: "USD/CAD",
    displayNameShort: "USD/CAD",
    category: "FX",
    csvFile: "USDCAD.csv",
    csvDir: RAW_PARTS,
    exchange: "OTC FX",
    backadjustmentStatus: "unknown",
    marketType: "spot",
    iconKey: "usdcad",
    firstDateEstimate: "2006-03-02",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },
  {
    assetId: "audjpy",
    symbol: "AUDJPY",
    displayName: "AUD/JPY",
    displayNameShort: "AUD/JPY",
    category: "FX",
    csvFile: "AUDJPY.csv",
    csvDir: RAW_PARTS,
    exchange: "OTC FX",
    backadjustmentStatus: "unknown",
    marketType: "spot",
    iconKey: "audjpy",
    firstDateEstimate: "2006-03-02",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },
  {
    assetId: "eurgbp",
    symbol: "EURGBP",
    displayName: "EUR/GBP",
    displayNameShort: "EUR/GBP",
    category: "FX",
    csvFile: "EURGBP.csv",
    csvDir: RAW_PARTS,
    exchange: "OTC FX",
    backadjustmentStatus: "unknown",
    marketType: "spot",
    iconKey: "eurgbp",
    firstDateEstimate: "2006-03-02",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },
  {
    assetId: "euraud",
    symbol: "EURAUD",
    displayName: "EUR/AUD",
    displayNameShort: "EUR/AUD",
    category: "FX",
    csvFile: "EURAUD.csv",
    csvDir: RAW_PARTS,
    exchange: "OTC FX",
    backadjustmentStatus: "unknown",
    marketType: "spot",
    iconKey: "euraud",
    firstDateEstimate: "2006-03-02",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },

  // ── Aktien ───────────────────────────────────────────────────────────────
  {
    assetId: "aapl",
    symbol: "NASDAQ:AAPL",
    displayName: "Apple Inc.",
    displayNameShort: "AAPL",
    category: "Aktien",
    csvFile: "AAPL.csv",
    csvDir: RAW_PARTS,
    exchange: "NASDAQ",
    backadjustmentStatus: "assumed_backadjusted",
    marketType: "spot",
    iconKey: "aapl",
    firstDateEstimate: "1990-01-02",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },
  {
    assetId: "msft",
    symbol: "NASDAQ:MSFT",
    displayName: "Microsoft Corp.",
    displayNameShort: "MSFT",
    category: "Aktien",
    csvFile: "MSFT.csv",
    csvDir: RAW_PARTS,
    exchange: "NASDAQ",
    backadjustmentStatus: "assumed_backadjusted",
    marketType: "spot",
    iconKey: "msft",
    firstDateEstimate: "1990-01-02",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },
  {
    assetId: "nvda",
    symbol: "NASDAQ:NVDA",
    displayName: "NVIDIA Corp.",
    displayNameShort: "NVDA",
    category: "Aktien",
    csvFile: "NVDA.csv",
    csvDir: RAW_PARTS,
    exchange: "NASDAQ",
    backadjustmentStatus: "assumed_backadjusted",
    marketType: "spot",
    iconKey: "nvda",
    firstDateEstimate: "1999-01-22",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },
  {
    assetId: "amzn",
    symbol: "NASDAQ:AMZN",
    displayName: "Amazon.com Inc.",
    displayNameShort: "AMZN",
    category: "Aktien",
    csvFile: "AMZN.csv",
    csvDir: RAW_PARTS,
    exchange: "NASDAQ",
    backadjustmentStatus: "assumed_backadjusted",
    marketType: "spot",
    iconKey: "amzn",
    firstDateEstimate: "1997-05-15",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },
  {
    assetId: "goog",
    symbol: "NASDAQ:GOOG",
    displayName: "Alphabet Inc.",
    displayNameShort: "GOOG",
    category: "Aktien",
    csvFile: "GOOG.csv",
    csvDir: RAW_PARTS,
    exchange: "NASDAQ",
    backadjustmentStatus: "assumed_backadjusted",
    marketType: "spot",
    iconKey: "goog",
    firstDateEstimate: "2004-08-19",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },
  {
    assetId: "jpm",
    symbol: "NYSE:JPM",
    displayName: "JPMorgan Chase",
    displayNameShort: "JPM",
    category: "Aktien",
    csvFile: "JPM.csv",
    csvDir: RAW_PARTS,
    exchange: "NYSE",
    backadjustmentStatus: "assumed_backadjusted",
    marketType: "spot",
    iconKey: "jpm",
    firstDateEstimate: "1990-01-02",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },
  {
    assetId: "xom",
    symbol: "NYSE:XOM",
    displayName: "Exxon Mobil Corp.",
    displayNameShort: "XOM",
    category: "Aktien",
    csvFile: "XOM.csv",
    csvDir: RAW_PARTS,
    exchange: "NYSE",
    backadjustmentStatus: "assumed_backadjusted",
    marketType: "spot",
    iconKey: "xom",
    firstDateEstimate: "1990-01-02",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },
  {
    assetId: "ko",
    symbol: "NYSE:KO",
    displayName: "Coca-Cola Co.",
    displayNameShort: "KO",
    category: "Aktien",
    csvFile: "KO.csv",
    csvDir: RAW_PARTS,
    exchange: "NYSE",
    backadjustmentStatus: "assumed_backadjusted",
    marketType: "spot",
    iconKey: "ko",
    firstDateEstimate: "1990-01-02",
    lastDateEstimate: "2026-03-02",
    completeYearsEstimate: 20,
  },

  // ── Monitoring futures / indices (registry stubs) ─────────────────────────
  { assetId: "gc1", symbol: "COMEX:GC1!", displayName: "Gold Futures", displayNameShort: "Gold", category: "Metalle", csvFile: "__yahoo__", exchange: "COMEX", backadjustmentStatus: "assumed_backadjusted", marketType: "continuous_futures", iconKey: "gold", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 20 },
  { assetId: "si1", symbol: "COMEX:SI1!", displayName: "Silver Futures", displayNameShort: "Silver", category: "Metalle", csvFile: "__yahoo__", exchange: "COMEX", backadjustmentStatus: "assumed_backadjusted", marketType: "continuous_futures", iconKey: "silver", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 20 },
  { assetId: "hg1", symbol: "COMEX:HG1!", displayName: "Copper Futures", displayNameShort: "Copper", category: "Metalle", csvFile: "__yahoo__", exchange: "COMEX", backadjustmentStatus: "assumed_backadjusted", marketType: "continuous_futures", iconKey: "copper", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 20 },
  { assetId: "pl1", symbol: "NYMEX:PL1!", displayName: "Platinum Futures", displayNameShort: "Platinum", category: "Metalle", csvFile: "__yahoo__", exchange: "NYMEX", backadjustmentStatus: "assumed_backadjusted", marketType: "continuous_futures", iconKey: "platinum", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 20 },
  { assetId: "pa1", symbol: "NYMEX:PA1!", displayName: "Palladium Futures", displayNameShort: "Palladium", category: "Metalle", csvFile: "__yahoo__", exchange: "NYMEX", backadjustmentStatus: "assumed_backadjusted", marketType: "continuous_futures", iconKey: "palladium", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 20 },
  { assetId: "cl1", symbol: "NYMEX:CL1!", displayName: "Crude Oil", displayNameShort: "Crude Oil", category: "Energie", csvFile: "__yahoo__", exchange: "NYMEX", backadjustmentStatus: "assumed_backadjusted", marketType: "continuous_futures", iconKey: "oil", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 20 },
  { assetId: "ng1", symbol: "NYMEX:NG1!", displayName: "Natural Gas", displayNameShort: "Natural Gas", category: "Energie", csvFile: "__yahoo__", exchange: "NYMEX", backadjustmentStatus: "assumed_backadjusted", marketType: "continuous_futures", iconKey: "natgas", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 20 },
  { assetId: "rb1", symbol: "NYMEX:RB1!", displayName: "Gasoline", displayNameShort: "Gasoline", category: "Energie", csvFile: "__yahoo__", exchange: "NYMEX", backadjustmentStatus: "assumed_backadjusted", marketType: "continuous_futures", iconKey: "oil", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 20 },
  { assetId: "fx_6a1", symbol: "6A1!", displayName: "AUD Futures", displayNameShort: "6A1!", category: "FX", csvFile: "__yahoo__", exchange: "CME", backadjustmentStatus: "unknown", marketType: "continuous_futures", iconKey: "aud", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 15 },
  { assetId: "fx_6b1", symbol: "6B1!", displayName: "GBP Futures", displayNameShort: "6B1!", category: "FX", csvFile: "__yahoo__", exchange: "CME", backadjustmentStatus: "unknown", marketType: "continuous_futures", iconKey: "gbp", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 15 },
  { assetId: "fx_6c1", symbol: "6C1!", displayName: "CAD Futures", displayNameShort: "6C1!", category: "FX", csvFile: "__yahoo__", exchange: "CME", backadjustmentStatus: "unknown", marketType: "continuous_futures", iconKey: "cad", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 15 },
  { assetId: "fx_6e1", symbol: "6E1!", displayName: "EUR Futures", displayNameShort: "6E1!", category: "FX", csvFile: "__yahoo__", exchange: "CME", backadjustmentStatus: "unknown", marketType: "continuous_futures", iconKey: "eur", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 15 },
  { assetId: "fx_6j1", symbol: "6J1!", displayName: "JPY Futures", displayNameShort: "6J1!", category: "FX", csvFile: "__yahoo__", exchange: "CME", backadjustmentStatus: "unknown", marketType: "continuous_futures", iconKey: "jpy", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 15 },
  { assetId: "fx_6n1", symbol: "6N1!", displayName: "NZD Futures", displayNameShort: "6N1!", category: "FX", csvFile: "__yahoo__", exchange: "CME", backadjustmentStatus: "unknown", marketType: "continuous_futures", iconKey: "nzd", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 15 },
  { assetId: "fx_6s1", symbol: "6S1!", displayName: "CHF Futures", displayNameShort: "6S1!", category: "FX", csvFile: "__yahoo__", exchange: "CME", backadjustmentStatus: "unknown", marketType: "continuous_futures", iconKey: "chf", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 15 },
  { assetId: "dxy", symbol: "DXY", displayName: "US Dollar Index", displayNameShort: "DXY", category: "FX", csvFile: "DXY.csv", csvDir: RAW_PARTS, exchange: "TVC", backadjustmentStatus: "unknown", marketType: "spot", iconKey: "dxy", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 15 },
  { assetId: "us30usd", symbol: "OANDA:US30USD", displayName: "US 30", displayNameShort: "US30", category: "Indizes", csvFile: "DOW30.csv", csvDir: RAW_PARTS, exchange: "OANDA", backadjustmentStatus: "unknown", marketType: "spot", iconKey: "dow", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 15 },
  { assetId: "nq1", symbol: "CME_MINI:NQ1!", displayName: "Nasdaq 100", displayNameShort: "NQ", category: "Indizes", csvFile: "__yahoo__", exchange: "CME", backadjustmentStatus: "assumed_backadjusted", marketType: "continuous_futures", iconKey: "nasdaq", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 15 },
  { assetId: "es1", symbol: "CME_MINI:ES1!", displayName: "S&P 500", displayNameShort: "ES", category: "Indizes", csvFile: "__yahoo__", exchange: "CME", backadjustmentStatus: "assumed_backadjusted", marketType: "continuous_futures", iconKey: "esSp", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 15 },
  { assetId: "fdax1", symbol: "EUREX:FDAX1!", displayName: "DAX", displayNameShort: "DAX", category: "Indizes", csvFile: "__yahoo__", exchange: "EUREX", backadjustmentStatus: "assumed_backadjusted", marketType: "continuous_futures", iconKey: "dax", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 15 },
  { assetId: "rty1", symbol: "CME_MINI:RTY1!", displayName: "Russell 2000", displayNameShort: "RTY", category: "Indizes", csvFile: "__yahoo__", exchange: "CME", backadjustmentStatus: "assumed_backadjusted", marketType: "continuous_futures", iconKey: "rty", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 15 },
  { assetId: "ym1", symbol: "CBOT_MINI:YM1!", displayName: "Dow Mini", displayNameShort: "YM", category: "Indizes", csvFile: "__yahoo__", exchange: "CBOT", backadjustmentStatus: "assumed_backadjusted", marketType: "continuous_futures", iconKey: "dowJones", firstDateEstimate: "1990-01-01", lastDateEstimate: "2026-06-01", completeYearsEstimate: 15 },
  { assetId: "meta", symbol: "NASDAQ:META", displayName: "Meta Platforms", displayNameShort: "META", category: "Aktien", csvFile: "META.csv", csvDir: RAW_PARTS, exchange: "NASDAQ", backadjustmentStatus: "assumed_backadjusted", marketType: "spot", iconKey: "meta", firstDateEstimate: "2012-05-18", lastDateEstimate: "2026-06-01", completeYearsEstimate: 12 },
];
