export const runtime = "edge";
import { NextResponse } from "next/server";
import type { AssetItem, AssetsResponse } from "@/lib/globe/globe-types";

const GLOBE_ASSETS: AssetItem[] = [
  // ── White Swan Portfolio ──
  { id: "gld_etf", name: "GLD (Gold ETF)", category: "White Swan Portfolio", iconKey: "gold", tvSource: "NYSE:GLD", symbol: "GLD", lat: 40.7, lng: -74.0, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 40.7, lng: -74.0, label: "New York", weight: 1 }] },
  { id: "gc1", name: "Gold Futures (GC1!)", category: "White Swan Portfolio", iconKey: "gold", tvSource: "COMEX:GC1!", symbol: "GC=F", lat: 40.7, lng: -74.0, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 40.7, lng: -74.0, label: "New York", weight: 1 }] },
  { id: "ym1", name: "Dow Jones Futures (YM1!)", category: "White Swan Portfolio", iconKey: "us", tvSource: "CME_MINI:YM1!", symbol: "YM=F", lat: 41.9, lng: -87.6, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 41.9, lng: -87.6, label: "Chicago", weight: 1 }] },
  { id: "nq1", name: "Nasdaq Futures (NQ1!)", category: "White Swan Portfolio", iconKey: "us", tvSource: "CME_MINI:NQ1!", symbol: "NQ=F", lat: 40.7, lng: -74.0, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 40.7, lng: -74.0, label: "New York", weight: 1 }] },
  { id: "ct1", name: "Cotton Futures (CT1!)", category: "White Swan Portfolio", iconKey: "cotton", tvSource: "ICEEUR:CT1!", symbol: "CT=F", lat: 34.0, lng: -81.0, country: "USA", color: "#e5e7eb", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 34.0, lng: -81.0, label: "Southeast USA", weight: 1 }] },
  { id: "ukx", name: "FTSE 100 (UKX)", category: "White Swan Portfolio", iconKey: "gb", tvSource: "ICEEUR:Z1!", symbol: "^FTSE", lat: 51.5, lng: -0.1, country: "UK", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 51.5, lng: -0.1, label: "London (United Kingdom)", weight: 1 }] },

  // ── Intraday MT ──
  { id: "eurusd_30m", name: "EUR/USD (30M)", category: "Intraday MT", iconKey: "eu", tvSource: "FX:EURUSD", symbol: "EURUSD=X", lat: 50.1, lng: 8.7, country: "Eurozone", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 50.1, lng: 8.7, label: "Frankfurt (Germany)", weight: 1 }] },
  { id: "dax_1h", name: "DAX (1H)", category: "Intraday MT", iconKey: "de", tvSource: "EUREX:FDAX1!", symbol: "^GDAXI", lat: 50.1, lng: 8.7, country: "Germany", color: "#f97316", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 50.1, lng: 8.7, label: "Frankfurt (Germany)", weight: 1 }] },
  { id: "gbpusd_30m", name: "GBP/USD (30M)", category: "Intraday MT", iconKey: "gb", tvSource: "FX:GBPUSD", symbol: "GBPUSD=X", lat: 51.5, lng: -0.1, country: "UK", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 51.5, lng: -0.1, label: "London (United Kingdom)", weight: 1 }] },
  { id: "dax_2h", name: "DAX (2H)", category: "Intraday MT", iconKey: "de", tvSource: "EUREX:FDAX1!", symbol: "^GDAXI", lat: 50.1, lng: 8.7, country: "Germany", color: "#fb923c", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 50.1, lng: 8.7, label: "Frankfurt (Germany)", weight: 1 }] },

  // ── Core Invest ──
  { id: "qqq", name: "QQQ (Nasdaq ETF)", category: "Core Invest", iconKey: "us", tvSource: "NASDAQ:QQQ", symbol: "QQQ", lat: 40.7, lng: -74.0, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 40.7, lng: -74.0, label: "New York", weight: 1 }] },
  { id: "gld_ci", name: "GLD (Gold ETF)", category: "Core Invest", iconKey: "gold", tvSource: "NYSE:GLD", symbol: "GLD", lat: 40.7, lng: -74.0, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 40.7, lng: -74.0, label: "New York", weight: 1 }] },
  { id: "spmo", name: "SPMO (Momentum ETF)", category: "Core Invest", iconKey: "us", tvSource: "NYSE:SPMO", symbol: "SPMO", lat: 40.7, lng: -74.0, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 40.7, lng: -74.0, label: "New York", weight: 1 }] },
  { id: "spy", name: "SPY (S&P 500 ETF)", category: "Core Invest", iconKey: "us", tvSource: "NYSE:SPY", symbol: "SPY", lat: 40.7, lng: -74.0, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 40.7, lng: -74.0, label: "New York", weight: 1 }] },
  { id: "hg1", name: "Copper Futures (HG1!)", category: "Core Invest", iconKey: "copper", tvSource: "COMEX:HG1!", symbol: "HG=F", lat: -33.5, lng: -70.7, country: "Chile", color: "#f97316", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: -33.5, lng: -70.7, label: "Santiago (Chile)", weight: 1 }] },
  { id: "6s1", name: "Swiss Franc (6S1!)", category: "Core Invest", iconKey: "ch", tvSource: "CME:6S1!", symbol: "CHF=X", lat: 46.9, lng: 7.4, country: "Switzerland", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 46.9, lng: 7.4, label: "Bern (Switzerland)", weight: 1 }] },
  { id: "glgg", name: "GLGG (Clean Water ETF)", category: "Core Invest", iconKey: "eu", tvSource: "LSE:GLGG", symbol: "GLGG.L", lat: 53.3, lng: -6.3, country: "Ireland", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 53.3, lng: -6.3, label: "Dublin", weight: 1 }] },
  { id: "fiw", name: "FIW (Water ETF)", category: "Core Invest", iconKey: "us", tvSource: "NYSE:FIW", symbol: "FIW", lat: 40.7, lng: -74.0, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 40.7, lng: -74.0, label: "New York", weight: 1 }] },

  // ── Crypto ──
  { id: "btcusd", name: "Bitcoin (BTC/USD)", category: "Crypto", iconKey: "btc", tvSource: "BITSTAMP:BTCUSD", symbol: "BTC-USD", lat: 37.4, lng: -122.1, country: "USA", color: "#f97316", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 37.4, lng: -122.1, label: "San Francisco", weight: 1 }] },
  { id: "ethusd", name: "Ethereum (ETH/USD)", category: "Crypto", iconKey: "eth", tvSource: "BITSTAMP:ETHUSD", symbol: "ETH-USD", lat: 37.4, lng: -122.1, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 37.4, lng: -122.1, label: "San Francisco", weight: 1 }] },
  { id: "xrpusd", name: "XRP/USD", category: "Crypto", iconKey: "btc", tvSource: "BITSTAMP:XRPUSD", symbol: "XRP-USD", lat: 37.4, lng: -122.1, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 37.4, lng: -122.1, label: "San Francisco", weight: 1 }] },
  { id: "solusd", name: "Solana (SOL/USD)", category: "Crypto", iconKey: "btc", tvSource: "COINBASE:SOLUSD", symbol: "SOL-USD", lat: 37.4, lng: -122.1, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 37.4, lng: -122.1, label: "San Francisco", weight: 1 }] },
  { id: "adausd", name: "Cardano (ADA/USD)", category: "Crypto", iconKey: "btc", tvSource: "COINBASE:ADAUSD", symbol: "ADA-USD", lat: 53.3, lng: -6.3, country: "Ireland", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 53.3, lng: -6.3, label: "Dublin", weight: 1 }] },
  { id: "dogeusd", name: "Dogecoin (DOGE/USD)", category: "Crypto", iconKey: "btc", tvSource: "BINANCE:DOGEUSDT", symbol: "DOGE-USD", lat: 37.4, lng: -122.1, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 37.4, lng: -122.1, label: "San Francisco", weight: 1 }] },

  // ── Macro ──
  { id: "dxy", name: "DXY (Dollar Index)", category: "Macro", iconKey: "us", tvSource: "TVC:DXY", symbol: "DX-Y.NYB", lat: 40.7, lng: -74.0, country: "USA", color: "#64748b", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 40.7, lng: -74.0, label: "New York", weight: 1 }] },
  { id: "vix", name: "VIX (Volatility Index)", category: "Macro", iconKey: "us", tvSource: "CBOE:VIX", symbol: "^VIX", lat: 41.9, lng: -87.6, country: "USA", color: "#dc2626", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 41.9, lng: -87.6, label: "Chicago", weight: 1 }] },
  { id: "tnx", name: "TNX (10Y Treasury)", category: "Macro", iconKey: "us", tvSource: "TVC:TNX", symbol: "^TNX", lat: 38.9, lng: -77.0, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 38.9, lng: -77.0, label: "Washington D.C.", weight: 1 }] },
  { id: "us2y", name: "US 2Y Yield", category: "Macro", iconKey: "us", tvSource: "TVC:US02Y", symbol: "^IRX", lat: 38.9, lng: -77.0, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 38.9, lng: -77.0, label: "Washington D.C.", weight: 1 }] },

  // ── Major FX ──
  { id: "usdjpy", name: "USD/JPY", category: "Major FX", iconKey: "jp", tvSource: "FX:USDJPY", symbol: "JPY=X", lat: 35.7, lng: 139.7, country: "Japan", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 35.7, lng: 139.7, label: "Tokyo (Japan)", weight: 1 }] },
  { id: "audusd", name: "AUD/USD", category: "Major FX", iconKey: "au", tvSource: "FX:AUDUSD", symbol: "AUDUSD=X", lat: -33.9, lng: 151.2, country: "Australia", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: -33.9, lng: 151.2, label: "Sydney (Australia)", weight: 1 }] },
  { id: "usdcad", name: "USD/CAD", category: "Major FX", iconKey: "ca", tvSource: "FX:USDCAD", symbol: "CAD=X", lat: 43.7, lng: -79.4, country: "Canada", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 43.7, lng: -79.4, label: "Toronto (Canada)", weight: 1 }] },
  { id: "nzdusd", name: "NZD/USD", category: "Major FX", iconKey: "au", tvSource: "FX:NZDUSD", symbol: "NZDUSD=X", lat: -36.9, lng: 174.8, country: "New Zealand", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: -36.9, lng: 174.8, label: "Auckland (New Zealand)", weight: 1 }] },
  { id: "usdchf_fx", name: "USD/CHF", category: "Major FX", iconKey: "ch", tvSource: "FX:USDCHF", symbol: "CHF=X", lat: 47.4, lng: 8.5, country: "Switzerland", color: "#D4AF37", defaultEnabled: true, showOnGlobe: false, locations: [{ lat: 47.4, lng: 8.5, label: "Zurich (Switzerland)", weight: 1 }] },

  // ── Cross Pairs ──
  { id: "eurgbp_fx", name: "EUR/GBP", category: "Cross Pairs", iconKey: "eu", tvSource: "FX:EURGBP", symbol: "EURGBP=X", lat: 48.9, lng: 2.3, country: "Eurozone", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 48.9, lng: 2.3, label: "Paris (France)", weight: 1 }, { lat: 51.5, lng: -0.1, label: "London (United Kingdom)", weight: 1 }] },
  { id: "eurjpy_fx", name: "EUR/JPY", category: "Cross Pairs", iconKey: "eu", tvSource: "FX:EURJPY", symbol: "EURJPY=X", lat: 50.1, lng: 8.7, country: "Eurozone", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 50.1, lng: 8.7, label: "Frankfurt (Germany)", weight: 1 }, { lat: 35.7, lng: 139.7, label: "Tokyo (Japan)", weight: 1 }] },
  { id: "gbpjpy_fx", name: "GBP/JPY", category: "Cross Pairs", iconKey: "gb", tvSource: "FX:GBPJPY", symbol: "GBPJPY=X", lat: 51.5, lng: -0.1, country: "UK", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 51.5, lng: -0.1, label: "London (United Kingdom)", weight: 1 }, { lat: 35.7, lng: 139.7, label: "Tokyo (Japan)", weight: 1 }] },
  { id: "audcad_fx", name: "AUD/CAD", category: "Cross Pairs", iconKey: "au", tvSource: "FX:AUDCAD", symbol: "AUDCAD=X", lat: -33.9, lng: 151.2, country: "Australia", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: -33.9, lng: 151.2, label: "Sydney (Australia)", weight: 1 }] },
  { id: "eurchf_fx", name: "EUR/CHF", category: "Cross Pairs", iconKey: "eu", tvSource: "FX:EURCHF", symbol: "EURCHF=X", lat: 47.4, lng: 8.5, country: "Switzerland", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 47.4, lng: 8.5, label: "Zurich (Switzerland)", weight: 1 }] },
  { id: "usdmxn_fx", name: "USD/MXN", category: "Cross Pairs", iconKey: "us", tvSource: "FX:USDMXN", symbol: "MXN=X", lat: 19.4, lng: -99.1, country: "Mexico", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 19.4, lng: -99.1, label: "Mexico City (Mexico)", weight: 1 }] },
  { id: "usdzar_fx", name: "USD/ZAR", category: "Cross Pairs", iconKey: "us", tvSource: "FX:USDZAR", symbol: "ZAR=X", lat: -26.2, lng: 28.0, country: "South Africa", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: -26.2, lng: 28.0, label: "Johannesburg (South Africa)", weight: 1 }] },
  { id: "usdtry_fx", name: "USD/TRY", category: "Cross Pairs", iconKey: "us", tvSource: "FX:USDTRY", symbol: "TRY=X", lat: 41.0, lng: 29.0, country: "Turkey", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 41.0, lng: 29.0, label: "Istanbul (Turkey)", weight: 1 }] },

  // ── Equities ──
  { id: "sp500_idx", name: "S&P 500 Index", category: "Equities", iconKey: "us", tvSource: "SP:SPX", symbol: "^GSPC", lat: 40.7, lng: -74.0, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 40.7, lng: -74.0, label: "New York", weight: 1 }] },
  { id: "nasdaq_idx", name: "Nasdaq Composite", category: "Equities", iconKey: "us", tvSource: "NASDAQ:IXIC", symbol: "^IXIC", lat: 40.7, lng: -74.0, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: false, locations: [{ lat: 40.7, lng: -74.0, label: "New York", weight: 1 }] },
  { id: "dow_idx", name: "Dow Jones Index", category: "Equities", iconKey: "us", tvSource: "DJ:DJI", symbol: "^DJI", lat: 40.7, lng: -74.0, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 40.7, lng: -74.0, label: "New York", weight: 1 }] },
  { id: "russell2k", name: "Russell 2000", category: "Equities", iconKey: "us", tvSource: "TVC:RUT", symbol: "^RUT", lat: 40.7, lng: -74.0, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 40.7, lng: -74.0, label: "New York", weight: 1 }] },
  { id: "dax_idx", name: "DAX 40 Index", category: "Equities", iconKey: "de", tvSource: "EUREX:FDAX1!", symbol: "^GDAXI", lat: 50.1, lng: 8.7, country: "Germany", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 50.1, lng: 8.7, label: "Frankfurt (Germany)", weight: 1 }] },
  { id: "cac40_idx", name: "CAC 40 Index", category: "Equities", iconKey: "eu", tvSource: "EURONEXT:PX1", symbol: "^FCHI", lat: 48.9, lng: 2.3, country: "France", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 48.9, lng: 2.3, label: "Paris (France)", weight: 1 }] },
  { id: "eurostoxx_idx", name: "Euro Stoxx 50", category: "Equities", iconKey: "eu", tvSource: "EUREX:FESX1!", symbol: "^STOXX50E", lat: 50.1, lng: 8.7, country: "Eurozone", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 50.1, lng: 8.7, label: "Frankfurt (Germany)", weight: 1 }] },
  { id: "nikkei_idx", name: "Nikkei 225", category: "Equities", iconKey: "jp", tvSource: "TVC:NI225", symbol: "^N225", lat: 35.7, lng: 139.7, country: "Japan", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 35.7, lng: 139.7, label: "Tokyo (Japan)", weight: 1 }] },
  { id: "hsi_idx", name: "Hang Seng Index", category: "Equities", iconKey: "jp", tvSource: "TVC:HSI", symbol: "^HSI", lat: 22.3, lng: 114.2, country: "Hong Kong", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 22.3, lng: 114.2, label: "Hong Kong", weight: 1 }] },
  { id: "asx200_idx", name: "ASX 200", category: "Equities", iconKey: "au", tvSource: "ASX:XJO", symbol: "^AXJO", lat: -33.9, lng: 151.2, country: "Australia", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: -33.9, lng: 151.2, label: "Sydney (Australia)", weight: 1 }] },
  { id: "ibex_idx", name: "IBEX 35", category: "Equities", iconKey: "eu", tvSource: "BME:IBC", symbol: "^IBEX", lat: 40.4, lng: -3.7, country: "Spain", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 40.4, lng: -3.7, label: "Madrid (Spain)", weight: 1 }] },
  { id: "mib_idx", name: "FTSE MIB", category: "Equities", iconKey: "eu", tvSource: "MIL:FTSEMIB", symbol: "FTSEMIB.MI", lat: 45.5, lng: 9.2, country: "Italy", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 45.5, lng: 9.2, label: "Milan (Italy)", weight: 1 }] },

  // ── Stocks ──
  { id: "aapl", name: "Apple (AAPL)", category: "Stocks", iconKey: "aapl", tvSource: "NASDAQ:AAPL", symbol: "AAPL", lat: 37.3, lng: -122.0, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 37.3, lng: -122.0, label: "Cupertino", weight: 1 }] },
  { id: "msft", name: "Microsoft (MSFT)", category: "Stocks", iconKey: "msft", tvSource: "NASDAQ:MSFT", symbol: "MSFT", lat: 47.6, lng: -122.1, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 47.6, lng: -122.1, label: "Redmond", weight: 1 }] },
  { id: "nvda", name: "Nvidia (NVDA)", category: "Stocks", iconKey: "nvda", tvSource: "NASDAQ:NVDA", symbol: "NVDA", lat: 37.4, lng: -122.0, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 37.4, lng: -122.0, label: "Santa Clara", weight: 1 }] },
  { id: "tsla", name: "Tesla (TSLA)", category: "Stocks", iconKey: "us", tvSource: "NASDAQ:TSLA", symbol: "TSLA", lat: 30.2, lng: -97.7, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 30.2, lng: -97.7, label: "Austin", weight: 1 }] },
  { id: "meta_s", name: "Meta (META)", category: "Stocks", iconKey: "meta", tvSource: "NASDAQ:META", symbol: "META", lat: 37.5, lng: -122.2, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 37.5, lng: -122.2, label: "Menlo Park", weight: 1 }] },
  { id: "amzn", name: "Amazon (AMZN)", category: "Stocks", iconKey: "amzn", tvSource: "NASDAQ:AMZN", symbol: "AMZN", lat: 47.6, lng: -122.3, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 47.6, lng: -122.3, label: "Seattle", weight: 1 }] },
  { id: "googl", name: "Alphabet (GOOGL)", category: "Stocks", iconKey: "googl", tvSource: "NASDAQ:GOOGL", symbol: "GOOGL", lat: 37.4, lng: -122.1, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 37.4, lng: -122.1, label: "Mountain View", weight: 1 }] },
  { id: "jpm", name: "JPMorgan (JPM)", category: "Stocks", iconKey: "us", tvSource: "NYSE:JPM", symbol: "JPM", lat: 40.7, lng: -74.0, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 40.7, lng: -74.0, label: "New York", weight: 1 }] },
  { id: "bac", name: "Bank of America (BAC)", category: "Stocks", iconKey: "us", tvSource: "NYSE:BAC", symbol: "BAC", lat: 35.2, lng: -80.8, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 35.2, lng: -80.8, label: "Charlotte", weight: 1 }] },
  { id: "gs", name: "Goldman Sachs (GS)", category: "Stocks", iconKey: "us", tvSource: "NYSE:GS", symbol: "GS", lat: 40.7, lng: -74.0, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 40.7, lng: -74.0, label: "New York", weight: 1 }] },
  { id: "xom", name: "Exxon Mobil (XOM)", category: "Stocks", iconKey: "oil", tvSource: "NYSE:XOM", symbol: "XOM", lat: 32.8, lng: -97.0, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 32.8, lng: -97.0, label: "Irving", weight: 1 }] },
  { id: "cvx", name: "Chevron (CVX)", category: "Stocks", iconKey: "oil", tvSource: "NYSE:CVX", symbol: "CVX", lat: 37.8, lng: -122.2, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 37.8, lng: -122.2, label: "San Ramon", weight: 1 }] },
  { id: "tsm", name: "TSMC (TSM)", category: "Stocks", iconKey: "jp", tvSource: "NYSE:TSM", symbol: "TSM", lat: 24.1, lng: 120.7, country: "Taiwan", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 24.1, lng: 120.7, label: "Hsinchu (Taiwan)", weight: 1 }] },
  { id: "sap_de", name: "SAP (SAP)", category: "Stocks", iconKey: "de", tvSource: "NYSE:SAP", symbol: "SAP", lat: 49.3, lng: 8.6, country: "Germany", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 49.3, lng: 8.6, label: "Walldorf (Germany)", weight: 1 }] },

  // ── Metals ──
  { id: "silver", name: "Silver", category: "Metals", iconKey: "silver", tvSource: "COMEX:SI1!", symbol: "SI=F", lat: 40.7, lng: -74.0, country: "USA", color: "#94a3b8", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 40.7, lng: -74.0, label: "New York", weight: 1 }] },
  { id: "platinum", name: "Platinum", category: "Metals", iconKey: "palladium", tvSource: "NYMEX:PL1!", symbol: "PL=F", lat: -25.7, lng: 28.2, country: "South Africa", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: -25.7, lng: 28.2, label: "Pretoria (South Africa)", weight: 1 }] },
  { id: "palladium", name: "Palladium", category: "Metals", iconKey: "palladium", tvSource: "NYMEX:PA1!", symbol: "PA=F", lat: 55.8, lng: 37.6, country: "Russia", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 55.8, lng: 37.6, label: "Norilsk (Russia)", weight: 1 }] },
  { id: "copper_spot", name: "Copper Spot", category: "Metals", iconKey: "copper", tvSource: "COMEX:HG1!", symbol: "HG=F", lat: -33.5, lng: -70.7, country: "Chile", color: "#f97316", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: -33.5, lng: -70.7, label: "Santiago (Chile)", weight: 1 }] },

  // ── Energy ──
  { id: "crude", name: "Crude Oil (WTI)", category: "Energy", iconKey: "oil", tvSource: "NYMEX:CL1!", symbol: "CL=F", lat: 29.7, lng: -95.4, country: "USA", color: "#78716c", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 26.3, lng: 50.1, label: "Dhahran (Saudi Arabia)", weight: 1 }, { lat: 29.7, lng: -95.4, label: "Houston", weight: 1 }] },
  { id: "brent", name: "Brent Oil", category: "Energy", iconKey: "oil", tvSource: "ICEEUR:B1!", symbol: "BZ=F", lat: 61.0, lng: 2.0, country: "North Sea", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 61.0, lng: 2.0, label: "North Sea", weight: 1 }] },
  { id: "natgas", name: "Natural Gas", category: "Energy", iconKey: "gas", tvSource: "NYMEX:NG1!", symbol: "NG=F", lat: 29.7, lng: -95.4, country: "USA", color: "#D4AF37", defaultEnabled: true, showOnGlobe: true, locations: [{ lat: 29.7, lng: -95.4, label: "Henry Hub", weight: 1 }] },
  { id: "heating_oil", name: "Heating Oil", category: "Energy", iconKey: "oil", tvSource: "NYMEX:HO1!", symbol: "HO=F", lat: 40.7, lng: -74.0, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 40.7, lng: -74.0, label: "New York", weight: 1 }] },
  { id: "gasoline", name: "RBOB Gasoline", category: "Energy", iconKey: "oil", tvSource: "NYMEX:RB1!", symbol: "RB=F", lat: 29.7, lng: -95.4, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 29.7, lng: -95.4, label: "Houston", weight: 1 }] },
  { id: "ttf_gas", name: "TTF Natural Gas", category: "Energy", iconKey: "gas", tvSource: "ICEEUR:TTF1!", symbol: "TTF=F", lat: 52.4, lng: 4.9, country: "Netherlands", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 52.4, lng: 4.9, label: "Amsterdam (Netherlands)", weight: 1 }] },
  { id: "uranium", name: "Uranium ETF (URA)", category: "Energy", iconKey: "us", tvSource: "NYSE:URA", symbol: "URA", lat: 52.1, lng: -106.7, country: "Canada", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 52.1, lng: -106.7, label: "Saskatoon (Canada)", weight: 1 }] },

  // ── Agriculture ──
  { id: "corn_f", name: "Corn Futures", category: "Agriculture", iconKey: "corn", tvSource: "CBOT:ZC1!", symbol: "ZC=F", lat: 41.9, lng: -87.6, country: "USA", color: "#eab308", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 41.9, lng: -87.6, label: "Chicago", weight: 1 }] },
  { id: "wheat_f", name: "Wheat Futures", category: "Agriculture", iconKey: "wheat", tvSource: "CBOT:ZW1!", symbol: "ZW=F", lat: 37.7, lng: -97.3, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 37.7, lng: -97.3, label: "Wichita (USA)", weight: 1 }] },
  { id: "soybean_f", name: "Soybean Futures", category: "Agriculture", iconKey: "soy", tvSource: "CBOT:ZS1!", symbol: "ZS=F", lat: -15.8, lng: -47.9, country: "Brazil", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: -15.8, lng: -47.9, label: "Brasilia (Brazil)", weight: 1 }] },
  { id: "coffee_f", name: "Coffee Futures", category: "Agriculture", iconKey: "coffee", tvSource: "ICEEUR:KC1!", symbol: "KC=F", lat: 9.0, lng: 38.7, country: "Ethiopia", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 9.0, lng: 38.7, label: "Addis Ababa (Ethiopia)", weight: 1 }] },
  { id: "cocoa_f", name: "Cocoa Futures", category: "Agriculture", iconKey: "cocoa", tvSource: "ICEEUR:CC1!", symbol: "CC=F", lat: 5.4, lng: -4.0, country: "Ivory Coast", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 5.4, lng: -4.0, label: "Abidjan (Cote d'Ivoire)", weight: 1 }] },
  { id: "sugar_f", name: "Sugar Futures", category: "Agriculture", iconKey: "sugar", tvSource: "ICEEUR:SB1!", symbol: "SB=F", lat: -23.5, lng: -46.6, country: "Brazil", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: -23.5, lng: -46.6, label: "Sao Paulo (Brazil)", weight: 1 }] },
  { id: "oj_f", name: "Orange Juice", category: "Agriculture", iconKey: "oj", tvSource: "ICEEUR:OJ1!", symbol: "OJ=F", lat: 25.8, lng: -80.2, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 25.8, lng: -80.2, label: "Florida (USA)", weight: 1 }] },
  { id: "cattle_f", name: "Live Cattle", category: "Agriculture", iconKey: "corn", tvSource: "CME:LE1!", symbol: "LE=F", lat: 32.8, lng: -97.0, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 32.8, lng: -97.0, label: "Texas (USA)", weight: 1 }] },
  { id: "hogs_f", name: "Lean Hogs", category: "Agriculture", iconKey: "corn", tvSource: "CME:HE1!", symbol: "HE=F", lat: 41.9, lng: -93.6, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 41.9, lng: -93.6, label: "Iowa (USA)", weight: 1 }] },
  { id: "lumber_f", name: "Lumber", category: "Agriculture", iconKey: "corn", tvSource: "CME:LBR1!", symbol: "LBS=F", lat: 49.3, lng: -123.0, country: "Canada", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 49.3, lng: -123.0, label: "Vancouver (Canada)", weight: 1 }] },

  // ── Bonds ──
  { id: "zb1", name: "US 30Y T-Bond", category: "Bonds", iconKey: "us", tvSource: "CBOT:ZB1!", symbol: "ZB=F", lat: 38.9, lng: -77.0, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 38.9, lng: -77.0, label: "Washington D.C.", weight: 1 }] },
  { id: "zn1", name: "US 10Y T-Note", category: "Bonds", iconKey: "us", tvSource: "CBOT:ZN1!", symbol: "ZN=F", lat: 38.9, lng: -77.0, country: "USA", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 38.9, lng: -77.0, label: "Washington D.C.", weight: 1 }] },
  { id: "bund_f", name: "German Bund", category: "Bonds", iconKey: "de", tvSource: "EUREX:FGBL1!", symbol: "FGBL=F", lat: 50.1, lng: 8.7, country: "Germany", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 50.1, lng: 8.7, label: "Frankfurt (Germany)", weight: 1 }] },
  { id: "gilt_f", name: "UK Gilt", category: "Bonds", iconKey: "gb", tvSource: "ICEEUR:R1!", symbol: "R=F", lat: 51.5, lng: -0.1, country: "UK", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 51.5, lng: -0.1, label: "London (United Kingdom)", weight: 1 }] },
  { id: "jgb_f", name: "Japan 10Y Bond", category: "Bonds", iconKey: "jp", tvSource: "TSE:JGB1!", symbol: "^TNX", lat: 35.7, lng: 139.7, country: "Japan", color: "#D4AF37", defaultEnabled: false, showOnGlobe: false, locations: [{ lat: 35.7, lng: 139.7, label: "Tokyo (Japan)", weight: 1 }] },
];

export async function GET() {
  const response: AssetsResponse = {
    updatedAt: new Date().toISOString(),
    count: GLOBE_ASSETS.length,
    items: GLOBE_ASSETS,
  };
  return NextResponse.json(response, {
    headers: { "Cache-Control": "public, max-age=3600, stale-while-revalidate=86400" },
  });
}
