export const monitoringFeatureFlags = {
  enableBasicCandleCharts: true,
  enableTradingViewDataCacheAgrar: true,
  enableStrategyTester: "lazy",
  enableTradeExecution: "lazy",
  enableSvgTradeOverlay: true,
  useNewTradeEngineVisuals: true,
  useLegacyTradeOverlay: false,
  enableFullscreenChart: "lazy",
  enableAllTabsBuild: true,
  enableAllStrategiesGrid: "lazy",
  enableIntradayMT: "lazy",
  enableLiveSnapshotMerge: false,
  enableLiveSnapshotPolling: false,
  enableRealtimePolling: false,
  useCustomOrangeJuiceEnginePilot: true,
  useCustomEs1EnginePilot: true,
  useCustomPa1EnginePilot: true,
  useCustomPl1EnginePilot: true,
  enableBacktestInReact: false,
  enableFullHistoryInGrid: false,
  enablePreloadInactiveTabs: false,
  enableDebugRendering: false,
} as const;
