import type { AgricultureMvaDataBinding, MvaAgricultureSymbol } from "./types";

const AGRICULTURE_BINDINGS: Record<MvaAgricultureSymbol, AgricultureMvaDataBinding> = {
  "ZW1!": {
    symbol: "ZW1!",
    displayName: "Wheat",
    tvSymbol: "CBOT:ZW1!",
    validatedOhlcCsvPath: null,
    liveOhlcJsonPath: "public/generated/monitoring/tradingview_data_cache/D/CBOT_ZW1_D.json",
    generatedPayloadPath: "public/generated/monitoring/all_s-17-wheat-macro-zw1.json",
    inputParamsXlsxPath: null,
    strategyReferenceCsvPath: null,
    tradeExportXlsxPath: null,
    tradeExportCsvPath: null,
    referenceEventsPath: "public/generated/monitoring/reference_events/zw1_zw1_d_reference_events.json",
    sourceType: "validated_tradingview_csv",
  },
  "ZC1!": {
    symbol: "ZC1!",
    displayName: "Corn",
    tvSymbol: "CBOT:ZC1!",
    validatedOhlcCsvPath: null,
    liveOhlcJsonPath: "public/generated/monitoring/tradingview_data_cache/D/CBOT_ZC1_D.json",
    generatedPayloadPath: "public/generated/monitoring/all_s-9-corn-macro-zc1.json",
    inputParamsXlsxPath: null,
    strategyReferenceCsvPath: null,
    tradeExportXlsxPath: null,
    tradeExportCsvPath: null,
    referenceEventsPath: "public/generated/monitoring/reference_events/zc1_zc1_d_reference_events.json",
    sourceType: "validated_tradingview_csv",
  },
  "ZS1!": {
    symbol: "ZS1!",
    displayName: "Soybeans",
    tvSymbol: "CBOT:ZS1!",
    validatedOhlcCsvPath: null,
    liveOhlcJsonPath: "public/generated/monitoring/tradingview_data_cache/D/CBOT_ZS1_D.json",
    generatedPayloadPath: "public/generated/monitoring/all_s-19-soybeans-macro-zs1.json",
    inputParamsXlsxPath: null,
    strategyReferenceCsvPath: null,
    tradeExportXlsxPath: null,
    tradeExportCsvPath: null,
    referenceEventsPath: null,
    sourceType: "validated_tradingview_csv",
  },
  "CC1!": {
    symbol: "CC1!",
    displayName: "Cocoa",
    tvSymbol: "ICEUS:CC1!",
    validatedOhlcCsvPath: null,
    liveOhlcJsonPath: "public/generated/monitoring/tradingview_data_cache/D/ICEUS_CC1_D.json",
    generatedPayloadPath: "public/generated/monitoring/all_s-8-cocoa-macro-cc1.json",
    inputParamsXlsxPath: null,
    strategyReferenceCsvPath: null,
    tradeExportXlsxPath: null,
    tradeExportCsvPath: null,
    referenceEventsPath: "public/generated/monitoring/reference_events/cc1_cc1_d_reference_events.json",
    sourceType: "validated_tradingview_csv",
  },
  "KC1!": {
    symbol: "KC1!",
    displayName: "Coffee",
    tvSymbol: "ICEUS:KC1!",
    validatedOhlcCsvPath: null,
    liveOhlcJsonPath: "public/generated/monitoring/tradingview_data_cache/D/ICEUS_KC1_D.json",
    generatedPayloadPath: "public/generated/monitoring/all_s-20-coffee-macro-kc1.json",
    inputParamsXlsxPath: null,
    strategyReferenceCsvPath: null,
    tradeExportXlsxPath: null,
    tradeExportCsvPath: null,
    referenceEventsPath: null,
    sourceType: "validated_tradingview_csv",
  },
  "SB1!": {
    symbol: "SB1!",
    displayName: "Sugar",
    tvSymbol: "ICEUS:SB1!",
    validatedOhlcCsvPath: null,
    liveOhlcJsonPath: "public/generated/monitoring/tradingview_data_cache/D/ICEUS_SB1_D.json",
    generatedPayloadPath: "public/generated/monitoring/all_s-16-sugar-macro-sb1.json",
    inputParamsXlsxPath: null,
    strategyReferenceCsvPath: null,
    tradeExportXlsxPath: null,
    tradeExportCsvPath: null,
    referenceEventsPath: null,
    sourceType: "validated_tradingview_csv",
  },
  "CT1!": {
    symbol: "CT1!",
    displayName: "Cotton",
    tvSymbol: "ICEUS:CT1!",
    validatedOhlcCsvPath: null,
    liveOhlcJsonPath: "public/generated/monitoring/tradingview_data_cache/D/ICEUS_CT1_D.json",
    generatedPayloadPath: "public/generated/monitoring/all_s-21-cotton-macro-ct1.json",
    inputParamsXlsxPath: null,
    strategyReferenceCsvPath: null,
    tradeExportXlsxPath: null,
    tradeExportCsvPath: null,
    referenceEventsPath: null,
    sourceType: "validated_tradingview_csv",
  },
  "OJ1!": {
    symbol: "OJ1!",
    displayName: "Orange Juice",
    tvSymbol: "ICEUS:OJ1!",
    validatedOhlcCsvPath: null,
    liveOhlcJsonPath: "public/generated/monitoring/tradingview_data_cache/D/ICEUS_OJ1_D.json",
    generatedPayloadPath: "public/generated/monitoring/all_s-12-orange-juice-macro-oj1.json",
    inputParamsXlsxPath: null,
    strategyReferenceCsvPath: null,
    tradeExportXlsxPath: null,
    tradeExportCsvPath: null,
    referenceEventsPath: "public/generated/monitoring/reference_events/oj1_oj1_d_reference_events.json",
    sourceType: "validated_tradingview_csv",
  },
};

export const MVA_AGRICULTURE_SYMBOLS = Object.keys(AGRICULTURE_BINDINGS) as MvaAgricultureSymbol[];

export function getAgricultureMvaBinding(symbol: string): AgricultureMvaDataBinding | null {
  const normalized = String(symbol || "").trim().toUpperCase() as MvaAgricultureSymbol;
  return AGRICULTURE_BINDINGS[normalized] ?? null;
}

export function getAgricultureMvaBindings(): AgricultureMvaDataBinding[] {
  return MVA_AGRICULTURE_SYMBOLS.map((symbol) => AGRICULTURE_BINDINGS[symbol]);
}
